@host = http://localhost:3333/providers/
@provider_id = 12f3e6bd-2e19-477f-8a77-e0789d2a4ebb
### Obtendo todos os providers except user_logged
GET {{host}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTE1MzY4NTIsImV4cCI6MTU5MTYyMzI1Miwic3ViIjoiMTljMDJlYTYtN2QxMS00YTQzLWFkZjMtNzM1N2U4MDRlZTQ4In0.m1zVmXHekJifTwXuwKeGQfpqwk9hBybHAliXmuZyVWM

### List Month Availability
GET {{host}}/{{provider_id}}/month-availability
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTIxNDU4MzgsImV4cCI6MTU5MjIzMjIzOCwic3ViIjoiMTljMDJlYTYtN2QxMS00YTQzLWFkZjMtNzM1N2U4MDRlZTQ4In0.qF4XTjkTtxKnKuoDGZ6-uh20LtF0UDxVYrMPP3JsCfU
Content-Type: application/json

{
  "year": 2020,
  "month": 6
}

### List Day Availability
GET {{host}}/{{provider_id}}/day-availability
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTIxNDU4MzgsImV4cCI6MTU5MjIzMjIzOCwic3ViIjoiMTljMDJlYTYtN2QxMS00YTQzLWFkZjMtNzM1N2U4MDRlZTQ4In0.qF4XTjkTtxKnKuoDGZ6-uh20LtF0UDxVYrMPP3JsCfU
Content-Type: application/json

{
  "year": 2020,
  "month": 6,
  "day": 14
}
