@host = http://localhost:3333/users
@formDataLimit = XXXXXXXXXXXXXXXXXXXX

###
POST {{host}}
Content-Type: application/json

{
  "name": "Wall Berg Morais",
  "email": "wallbergmirandamorais2@gmail.com",
  "password": "paparroz"
}

###
PATCH {{host}}/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTI2MjE0MTYsImV4cCI6MTU5MjcwNzgxNiwic3ViIjoiMTljMDJlYTYtN2QxMS00YTQzLWFkZjMtNzM1N2U4MDRlZTQ4In0.z5UswdSHdpMa467mhuoYGlY7WTYwG6trDP6E75DJVzA
Content-Type: multipart/form-data; boundary={{formDataLimit}}

--{{formDataLimit}}
Content-Disposition: form-data; name="avatar"; filename="profile.jpg"
Content-Type: image/jpg

< ./../profile.jpg
--{{formDataLimit}}--
