@tokenUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQzNDcxODAsImV4cCI6MTU5NDQzMzU4MCwic3ViIjoiM2E4MDczODMtNmE4Yi00MTA0LWJlZmItZGQzZjZiODdlMTU0In0.9YovR_me2HY9m5CgDt4nEXGPzfxfg5QnrKz4ajdv1vg
@tokenProvider = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTM2NjA2MTQsImV4cCI6MTU5Mzc0NzAxNCwic3ViIjoiM2E4MDczODMtNmE4Yi00MTA0LWJlZmItZGQzZjZiODdlMTU0In0.jntMuiS2DN2AtvnQGYBGfgD818Ak0qw94JcWYF56eSo

#################################################################
### Create Appointment
#################################################################
POST {{base_url}}/appointments
Content-Type: application/json
Authorization: Bearer {{tokenUser}}

{
  "provider_id": "19c02ea6-7d11-4a43-adf3-7357e804ee48",
  "date": "2020-07-10 9:00:00"
}
