@tokenUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQxNzEzNzUsImV4cCI6MTU5NDI1Nzc3NSwic3ViIjoiM2E4MDczODMtNmE4Yi00MTA0LWJlZmItZGQzZjZiODdlMTU0In0.lw2mng3b6FBBdmyA0vGpKxALNQffo7oMU7wASR-g_14
@tokenProvider = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTM2NjA2MTQsImV4cCI6MTU5Mzc0NzAxNCwic3ViIjoiM2E4MDczODMtNmE4Yi00MTA0LWJlZmItZGQzZjZiODdlMTU0In0.jntMuiS2DN2AtvnQGYBGfgD818Ak0qw94JcWYF56eSo

#################################################################
### Create Appointment
#################################################################
POST {{base_url}}/appointments
Content-Type: application/json
Authorization: Bearer {{tokenUser}}

{
  "provider_id": "19c02ea6-7d11-4a43-adf3-7357e804ee48",
  "date": "2020-07-08 18:00:00"
}
