#################################################################
## Pedindo a recuperação de senha
#################################################################
POST {{base_url}}/password/forgot
Content-Type: application/json

{
  "email": "wallbergmirandamorais@gmail.com"
}

#################################################################
### Reset de Senha!
#################################################################
POST {{base_url}}/password/reset
Content-Type: application/json

{
  "password": "123123",
  "password_confirmation": "123123",
  "token": "ae876269-935c-49b9-ae9c-9508acd8530d"
}
