@host = http://localhost:3333/appointments

### Create Appointment
POST {{host}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTIxNDU4MzgsImV4cCI6MTU5MjIzMjIzOCwic3ViIjoiMTljMDJlYTYtN2QxMS00YTQzLWFkZjMtNzM1N2U4MDRlZTQ4In0.qF4XTjkTtxKnKuoDGZ6-uh20LtF0UDxVYrMPP3JsCfU

{
  "provider_id": "12f3e6bd-2e19-477f-8a77-e0789d2a4ebb",
  "date": "2020-06-14T13:00:00-03:00"
}

### List All Appointment
GET {{host}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODczMjkxNzYsImV4cCI6MTU4NzQxNTU3Niwic3ViIjoiOWNhNjA5M2MtMTZlNC00YjgxLTk5OTQtZTg5ZWZmYzJiMjkyIn0.MppTL48ge08WgiGcXECxGs7E6O-p-mBxLPYdExTDYiI
