@host = http://localhost:3333/appointments

### Create Appointment
POST {{host}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODczMjkxNzYsImV4cCI6MTU4NzQxNTU3Niwic3ViIjoiOWNhNjA5M2MtMTZlNC00YjgxLTk5OTQtZTg5ZWZmYzJiMjkyIn0.MppTL48ge08WgiGcXECxGs7E6O-p-mBxLPYdExTDYiI

{
  "provider_id": "1cfe617e-0be9-4cff-8c47-4af6c482caa3",
  "date": "{{$datetime iso8601}}"
}

### List All Appointment
GET {{host}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODczMjkxNzYsImV4cCI6MTU4NzQxNTU3Niwic3ViIjoiOWNhNjA5M2MtMTZlNC00YjgxLTk5OTQtZTg5ZWZmYzJiMjkyIn0.MppTL48ge08WgiGcXECxGs7E6O-p-mBxLPYdExTDYiI
