@host = http://localhost:3333/password/

## Pedindo a recuperação de senha
POST {{host}}/forgot
Content-Type: application/json

{
  "email": "wallbergmirandamorais@gmail.com"
}

###
POST {{host}}/reset
Content-Type: application/json

{
  "password": "123123",
  "token": "d158b9ed-a0bf-42e2-92ac-752671c0145c"
}
