@host = http://localhost:3333/password/

## Pedindo a recuperação de senha
POST {{host}}/forgot
Content-Type: application/json

{
  "email": "wallbergmirandamorais@gmail.com"
}

###
POST {{host}}/reset
Content-Type: application/json

{
  "password": "123123",
  "token": "ae876269-935c-49b9-ae9c-9508acd8530d"
}
