@host = http://localhost:3333/profile/

### Mostrango o Profile
GET {{host}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTE0MTI4MjksImV4cCI6MTU5MTQ5OTIyOSwic3ViIjoiMTljMDJlYTYtN2QxMS00YTQzLWFkZjMtNzM1N2U4MDRlZTQ4In0.qmD9zbvXsj2RaK8dVse6IdZgxS8AOBEwDIldrZUq_Zo

### Atualizando o Profile
PUT {{host}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTE0MTI4MjksImV4cCI6MTU5MTQ5OTIyOSwic3ViIjoiMTljMDJlYTYtN2QxMS00YTQzLWFkZjMtNzM1N2U4MDRlZTQ4In0.qmD9zbvXsj2RaK8dVse6IdZgxS8AOBEwDIldrZUq_Zo
Content-Type: application/json

{
  "name": "Wall Berg M.",
  "email": "wallbergmirandamorais@gmail.com",
  "old_password": "123123",
  "password": "123456"
}
